#!/bin/bash
tmppath="$1.tmp"
curpath=`pwd`
git pull upstream master
cd "$1"
sourcepath=`pwd`
mkdir "$tmppath"
git checkout-index -a -f --prefix="$tmppath/"
cd "$tmppath"
rm -rf release/
rm -rf screenshots/
rm -rf scripts/
rm -rf deploy/
rm -rf dht/entangled_orig/
rm -rf devops/
rm -rf tests/dht/
rm -rf tests/e2e/
rm -rf tests/experiments/
cp -r * "$curpath"
diff --brief -r "$curpath" "$sourcepath" | grep -v ".git" | grep -v "__pycache__" | grep -v ".pyc" | grep -v ".DS_Store" | grep "Only in"
cd "$curpath"
rm -rf "$tmppath"
find . -type f -name "*.py" -exec sed -i '' -e 's/_Debug = True/_Debug = False/g' {} +
git status
